### ISSUE TITLE
Add clarification to transaction failed message

### ISSUE THREAD

**Issue by ozzt** [Lemmmy/KristPay2#1]
Right now, the transaction failed message says
>Transaction failed. Try again later, or contant an admin.

but you can also get this message by making a typo in the address. I recommend adding something like "Did you make a typo in the address?" to prevent confusion because this message makes it seem like Krist is currently offline.

**Comment by Lemmmy** [comment]
I can probably also add specific handling for "address not found" - pretty sure there's an error for that and I just forgot to handle it.
